// Generated by CoffeeScript 1.7.1
(function() {
  var Rpc,
    __slice = [].slice;

  Rpc = (function() {
    function Rpc() {}

    Rpc.prototype.connect = function(dsn) {};

    Rpc.prototype.call = function() {
      var args, method;
      method = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    };

    return Rpc;

  })();

  module.exports = Rpc;

}).call(this);
