// Generated by CoffeeScript 1.7.1
(function() {
  var Mongoose;

  Mongoose = (function() {
    function Mongoose() {}

    return Mongoose;

  })();

  module.exports = new Mongoose;

}).call(this);
