// Generated by CoffeeScript 1.8.0
(function() {
  var Client, axon, rpc;

  axon = require('axon');

  rpc = require('axon-rpc');

  Client = (function() {
    function Client() {
      this._req = axon.socket('req');
      this._client = new rpc.Client(this._req);
    }

    Client.prototype.connect = function() {
      return this._req.connect.apply(this._req, arguments);
    };

    Client.prototype.call = function() {
      return this._client.call.apply(this._client, arguments);
    };

    Client.prototype.methods = function() {
      return this._client.methods.apply(this._client, arguments);
    };

    return Client;

  })();

  module.exports = Client;

}).call(this);
