// Generated by CoffeeScript 1.7.1
(function() {
  var axon, client, req, rpc;

  axon = require('axon');

  rpc = require('axon-rpc');

  req = axon.socket('req');

  client = new rpc.Client(req);

  client.connect = function() {
    return req.connect.apply(req, arguments);
  };

  module.exports = client;

}).call(this);
