// Generated by CoffeeScript 1.7.1
(function() {
  var Connector;

  Connector = (function() {
    function Connector(group) {
      this.group = group;
      this.provider = 'mongo';
    }

    Connector.prototype.connect = function(dsn) {};

    Connector.prototype.provider = function(provider) {
      this.provider = provider;
      return this;
    };

    return Connector;

  })();

  module.exports = Connector;

}).call(this);
