// Generated by CoffeeScript 1.8.0
(function() {
  var limbo;

  limbo = require('./limbo');

  limbo.Manager = require('./manager');

  limbo.mongoose = require('mongoose');

  module.exports = limbo;

}).call(this);
