// Generated by CoffeeScript 1.12.4
(function() {
  var Limbo, limbo;

  Limbo = (function() {
    function Limbo() {
      this._providers = {};
    }

    Limbo.prototype.use = function(group, options) {
      var Provider, provider;
      if (options == null) {
        options = {};
      }
      if (!this._providers[group]) {
        provider = options.provider;
        provider || (provider = 'mongo');
        Provider = require("./providers/" + provider);
        options.group = group;
        this._providers[group] = new Provider(options);
      }
      return this._providers[group];
    };

    return Limbo;

  })();

  limbo = new Limbo;

  limbo.Limbo = Limbo;

  module.exports = limbo;

}).call(this);
