// Generated by CoffeeScript 1.7.1
(function() {
  var Manager;

  Manager = (function() {
    function Manager(model) {
      var foo, method;
      this.model = model;
      for (method in model) {
        foo = model[method];
        if (typeof foo === 'function' && (this[method] == null)) {
          (function(_this) {
            return (function(method, foo) {
              return _this[method] = function() {
                return foo.apply(model, arguments);
              };
            });
          })(this)(method, foo);
        }
      }
    }

    return Manager;

  })();

  module.exports = Manager;

}).call(this);
