// Generated by CoffeeScript 1.8.0
(function() {
  var Manager, ignoreMethods, _bind,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  _bind = function(fn, me) {
    return function() {
      return fn.apply(me, arguments);
    };
  };

  ignoreMethods = ['constructor', 'model'];

  Manager = (function() {
    function Manager(model) {
      var method, methodName;
      for (methodName in this) {
        method = this[methodName];
        if (typeof method === 'function' && __indexOf.call(ignoreMethods, methodName) < 0) {
          this[methodName] = _bind(method, this);
        }
      }
      for (methodName in model) {
        method = model[methodName];
        if (typeof method === 'function' && (this[methodName] == null)) {
          this[methodName] = _bind(method, model);
        }
      }
      this.model = model;
    }

    return Manager;

  })();

  module.exports = Manager;

}).call(this);
