// Generated by CoffeeScript 1.7.1
(function() {
  var Server, axon, rpc;

  axon = require('axon');

  rpc = require('axon-rpc');

  Server = (function() {
    function Server() {
      this._rep = axon.socket('rep');
      this._server = new rpc.Server(this._rep);
    }

    Server.prototype.bind = function() {
      return this._rep.bind.apply(this._rep, arguments);
    };

    Server.prototype.expose = function() {
      return this._server.expose.apply(this._server, arguments);
    };

    return Server;

  })();

  module.exports = Server;

}).call(this);
