// Generated by CoffeeScript 1.7.1
(function() {
  var axon, rep, rpc, server;

  axon = require('axon');

  rpc = require('axon-rpc');

  rep = axon.socket('rep');

  server = new rpc.Server(rep);

  server.bind = function() {
    return rep.bind.apply(rep, arguments);
  };

  module.exports = server;

}).call(this);
